apiVersion: v1
kind: Service
metadata:
  labels:
    app: kcd-demo-app
  name: kcd-demo-app
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  ports:
    - name: http-rest
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: http-metrics
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: kcd-demo-app
  type: ClusterIP